import { info } from 'autoprefixer'
import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Bookmark Landing Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossOrigin="anonymous"/>
      </Head>
      <header>
        <nav className="container flex items-center py-4 mt-4 sm:mt-12">
          <div className='py-1'>
            <img src='./imgs/logo-bookmark.svg' alt="" />
          </div>
            <ul className='items-center justify-end flex-1 hidden gap-12 text-xs uppercase sm:flex text-bookmark-blue'>
              <li className='cursor-pointer'>Features</li>
              <li className='cursor-pointer'>Pricing</li>
              <li className='cursor-pointer'>Contact</li>
              <button type='button' className='py-3 uppercase rounded-md px-7 bg-bookmark-red text-bookmark-white'>Login</button>
            </ul>
            <div className='flex justify-end flex-1 sm:hidden'>
              <i className='text-2xl fas fa-bars'></i>
            </div>
        </nav>
      </header> 
      
      <section className='relative'>
        <div className='container flex flex-col-reverse items-center gap-12 lg:flex-row mt-14 lg:mt-28'>
          <div className='flex flex-col items-center flex-1 lg:items-start'>
            <h2 className='mb-6 text-3xl text-center text-bookmark-blue lg:text-5xl lg:text-left'>
              A Simple Bookmark Manager
            </h2>
            <p className='mb-6 text-lg text-center text-bookmark-grey lg:text-left'>
              A clean and simple interface to organize your favourite website. Open a new browser tab and screen
              load instantly. try it fot free
            </p>
            <div className='flex flex-wrap justify-center gap-6'>
              <button type='button' className='btn btn-purple hover:bg-bookmark-white hover:text-bookmark-purple'>Get it on chrome</button>
              <button type='button' className='btn btn-white hover:bg-bookmark-purple hover:text-bookmark-white'>Get it on firefox</button>
            </div>
          </div>
          <div className='z-10 flex justify-center flex-1 mb-10 md:mb-16 lg:mb-0'>
            <img className='w-5/6 h-5/6 sm:w-3/4 sm:h-3 md:w-full md:h-full' src='./imgs/hero-bg.png' alt=''/>
          </div>
        </div>

        <div className='hidden md:block overflow-hidden bg-bookmark-purple rounded-l-full absolute h-80 w-2/4 top-32 right-0'>
        </div>
      </section>
      {/* featue-1 */}
      <section className='bg-bookmark-white py-20 mt-20 lg:mt-60'>
        <div className='sm:w-3/4 lg:w-5/12 mx-auto px-2'>
          <h1 className='text-3xl text-center text-bookmark-blue'>Features</h1>
          <p className='text-center text-bookmark-grey mt-4'>
              A clean and simple interface to organize your favourite website. Open a new browser tab and screen
              load instantly. try it fot free
            </p>
        </div>
        <div className='relative mt-20 lg:mt-24'>
          <div className='container flex flex-col lg:flex-row items-center justify-center gap-x-24'>
            <div className='flex flex-col justify-center z-10 mb-10 lg:mb-0'>
            <img className='w-5/6 h-5/6 sm:w-3/4 sm:h-3 md:w-full md:h-full' src="./imgs/illustration-features-tab-1.png" alt=''/>
            </div>
            <div className='flex flex-1 flex-col items-center lg:items-start'>
              <h1 className='text-3xl text-bookmark-blue'>Bookmark in one click</h1>
              <p className='text-bookmark-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full'>
                A clean and simple interface to organize your favourite website. Open a new browser tab and screen
                load instantly. try it fot free
              </p>
              <button type='button' className='btn btn-purple hover:bg-bookmark-white hover:text-bookmark-purple'>
                More Info</button>
            </div>
          </div>

          <div className='hidden lg:block overflow-hidden bg-bookmark-purple rounded-r-full absolute h-80 w-2/4 -bottom-24 -left-36'>
          </div>
        </div>
      {/* featue-2 */}
        <div className='relative mt-20 lg:mt-52'>
          <div className='container flex flex-col lg:flex-row-reverse items-center justify-center gap-x-24'>
            <div className='flex flex-col justify-center z-10 mb-10 lg:mb-0'>
            <img className='w-5/6 h-5/6 sm:w-3/4 sm:h-3 md:w-full md:h-full' src="./imgs/illustration-features-tab-2.png" alt=''/>
            </div>
            <div className='flex flex-1 flex-col items-center lg:items-start'>
              <h1 className='text-3xl text-bookmark-blue'>Bookmark in one click</h1>
              <p className='text-bookmark-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full'>
                A clean and simple interface to organize your favourite website. Open a new browser tab and screen
                load instantly. try it fot free
              </p>
              <button type='button' className='btn btn-purple hover:bg-bookmark-white hover:text-bookmark-purple'>
                More Info</button>
            </div>
          </div>

          <div className='hidden lg:block overflow-hidden bg-bookmark-purple rounded-l-full absolute h-80 w-2/4 -bottom-24 -right-36'>
          </div>
        </div>
      {/* featue-3 */}
        
        <div className='relative mt-20 lg:mt-52'>
          <div className='container flex flex-col lg:flex-row items-center justify-center gap-x-24'>
            <div className='flex flex-col justify-center z-10 mb-10 lg:mb-0'>
            <img className='w-5/6 h-5/6 sm:w-3/4 sm:h-3 md:w-full md:h-full' src="./imgs/illustration-features-tab-3.png" alt=''/>
            </div>
            <div className='flex flex-1 flex-col items-center lg:items-start'>
              <h1 className='text-3xl text-bookmark-blue'>Bookmark in one click</h1>
              <p className='text-bookmark-grey my-4 text-center lg:text-left sm:w-3/4 lg:w-full'>
                A clean and simple interface to organize your favourite website. Open a new browser tab and screen
                load instantly. try it fot free
              </p>
              <button type='button' className='btn btn-purple hover:bg-bookmark-white hover:text-bookmark-purple'>
                More Info</button>
            </div>
          </div>

          <div className='hidden lg:block overflow-hidden bg-bookmark-purple rounded-r-full absolute h-80 w-2/4 -bottom-24 -left-36'>
          </div>
        </div>

        <section className='py-20 mt-20'>
          <div className='sm:w-3/4 lg:w-5/12 mx-auto px-2'>
            <h1 className='text-center text-3xl text-bookmark-blue'>Download the extension</h1>
          <p className='mt-4 text-center text-bookmark-grey'>
              A clean and simple interface to organize your favourite website. Open a new browser tab and screen
              load instantly. try it fot free
            </p>
          </div>
          <div className='container grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-16 max-w-screen-lg mt-16'>
            <div className='flex flex-col rounded-md shadow-md lg:mb-16'>
                <div className='p-6 flex flex-col items-center'>
                    <img src='./imgs/logo-chrome.svg' alt=''/>
                    <h3 className='mt-5  text-bookmark-blue text-lg'>Add to chrome</h3>
                    <p className='mb-2 text-bookmark-grey font-light'>Minimum version 62</p>
                </div>
                <hr className='border-b border-bookmark-white'/>
                <div className='flex p-6'>
                  <button type='button' className='flex-1 btn btn-purple hover:bg-bookmark-white hover:text-bookmark-blue'>Add & Install extension</button>
                </div>
            </div>

            <div className='flex flex-col rounded-md shadow-md lg:mt-8 lg:mb-8'>
                <div className='p-6 flex flex-col items-center'>
                    <img src='./imgs/logo-firefox.svg' alt=''/>
                    <h3 className='mt-5  text-bookmark-blue text-lg'>Add to chrome</h3>
                    <p className='mb-2 text-bookmark-grey font-light'>Minimum version 62</p>
                </div>
                <hr className='border-b border-bookmark-white'/>
                <div className='flex p-6'>
                  <button type='button' className='flex-1 btn btn-purple hover:bg-bookmark-white hover:text-bookmark-blue'>Add & Install extension</button>
                </div>
            </div>

            <div className='flex flex-col rounded-md shadow-md lg:mt-16'>
                <div className='p-6 flex flex-col items-center'>
                    <img src='./imgs/logo-opera.svg' alt=''/>
                    <h3 className='mt-5  text-bookmark-blue text-lg'>Add to chrome</h3>
                    <p className='mb-2 text-bookmark-grey font-light'>Minimum version 62</p>
                </div>
                <hr className='border-b border-bookmark-white'/>
                <div className='flex p-6'>
                  <button type='button' className='flex-1 btn btn-purple hover:bg-bookmark-white hover:text-bookmark-blue'>Add & Install extension</button>
                </div>
            </div>
          </div>

        </section>

        <section className='bg-bookmark-white py-20'>
          <div className='container'>
            <div className='sm:w-3/4 lg:w-5/12 mx-auto px-2'>
              <h1 className='text-3xl text-center text-bookmark-blue'>Download the extension</h1>
            <p className='mt-4 text-center text-bookmark-grey'>
              A clean and simple interface to organize your favourite website. Open a new browser tab and screen
              load instantly. try it fot free
            </p>
            </div>
            <div className='flex flex-col sm:w-3/4 lg:w-5/12 mt-12 mx-auto'>
              <div className='flex items-center border-b py-4'>
                <span className='flex-1'> what is bookmark</span>
                <i className='fas fa-chevron-down'/>
              </div>
              <div className='flex items-center border-b py-4'>
                <span className='flex-1'> what is bookmark</span>
                <i className='fas fa-chevron-down'/>
              </div>
              <div className='flex items-center border-b py-4'>
                <span className='flex-1'> what is bookmark</span>
                <i className='fas fa-chevron-down'/>
              </div>
              <button type='button' className='flex self-center mt-5 btn btn-purple hover:bg-bookmark-white hover:text-bookmark-blue'>More Info</button>

            </div>
          </div>
        </section>
        
        <section className='bg-bookmark-purple text-bookmark-white py-20'>
          <div className='container'>
            <div className='sm:w-3/4 lg:w-5/12 mx-auto '>
              <p className='font-light uppercase text-center mb-8'>35,000+ ALREADY JOINED</p>
              <h1 className='text-center text-3xl'>stay upto-date with what we are doing</h1>
              <div className='flex flex-col sm:flex-row gap-6 mt-8'>
                <input className='px-2 py-3 flex-1 rounded-md text-bookmark-blue focus:outline-none' type="text" placeholder='Enter your email address'/>
                <button type='button' className='btn bg-bookmark-red'>Contact Us</button>
              </div>
            </div>
          </div>
        </section>
        <section className='bg-bookmark-blue py-8'>
          <div className='container flex flex-col md:flex-row items-center'>
            <div className='flex flex-1 flex-wrap items-center justify-center md:justify-start gap-12'>
              <img src='./imgs/logo-bookmark-white.png' alt=''/>
              <u1 className="flex text-bookmark-white uppercase gap-12  text-xs">
                <li className='cursor-pointer'>Features</li>
                <li className='cursor-pointer'>Pricing</li>
                <li className='cursor-pointer'>Contact</li>
              </u1>
            </div>
          </div>
        </section>
      </section>
    </div>
  )
}
